Update block-pushes.yml

diff --git a/.github/workflows/block-pushes.yml b/.github/workflows/block-pushes.yml
--- a/.github/workflows/block-pushes.yml
+++ b/.github/workflows/block-pushes.yml
@@ -15,9 +15,4 @@ jobs:
     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
     - run: echo "Pushes to this branch are not allowed."
     - name: Check if the commit was done through a PR
-    - run: |
-        if [ "${{ github.event_name }}" = "push" ]; then
-          echo "Direct commits to the main branch are not allowed. Please use a pull request."
-          exit 1
-        fi
-    # - run: exit 1 # This exits with a non-zero code, which fails the job and blocks the push
+    - run: exit 1 # This exits with a non-zero code, which fails the job and blocks the push
